server:
  port: 8094
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp_edutech_fee
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver # Use cj for modern drivers
  jpa:
    hibernate:
      ddl-auto: update # Options: none, update, create, create-drop, validate
    show-sql: true # Log SQL queries to the console